# --- Gateway Connection ---
gateways:
  postgres:
    connection:
      type: postgres
      host: ${POSTGRES_HOST}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      port: 5432
      database: ${POSTGRES_DB}

default_gateway: postgres

# --- Model Defaults ---
model_defaults:
  dialect: postgres
  start: 2025-08-03
  cron: '@daily'
  
# --- Linting Rules ---
lint:
  rules:
    - qualifytables
    - avoidselectstarexpansion



