# --- Gateway Connection ---
gateways:
  postgres:
    type: postgres
    connection: "postgresql://postgres:postgres@172.20.0.1:5432/analytics"

default_gateway: postgres

# --- Model Defaults ---
model_defaults:
  dialect: postgres
  start: 2025-08-10
  cron: '@daily'

# --- Linting Rules ---
linter:
  enabled: false
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion





