
# --- Gateway Connection ---
gateways:
  postgres:
    connection: "postgresql://postgres:postgres@172.20.0.1:5432/analytics"

default_gateway: postgres

# --- Model Defaults ---
model_defaults:
  dialect: postgres        # SQL dialect
  start: 2025-08-10        # Start date for backfill history
  cron: '@daily'           # Default schedule for models (can override per model)

# --- Linting Rules ---
linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
