gateways:
  postgres:
    connection:
      type: postgres
      host: 2xxaud.stackhero-network.com
      user: admin
      password: GUysEWwFsdX0W9rHJOsXY55SYAnfW346
      port: 5432
      database: analytics
      concurrent_tasks: 4
      pretty_sql: True
      connect_timeout: 20
      sslmode: require

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2025-08-10
  cron: '@​daily'

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion